//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    
    public partial class BGS_GetUserDetailsForVoter_Result
    {
        public int GradingID { get; set; }
        public string EmpID { get; set; }
        public string DueDate { get; set; }
        public string UserType { get; set; }
        public string Name { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> IsVoterSubmit { get; set; }
        public string RoleName { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string DeptName { get; set; }
    }
}
