//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    
    public partial class BGS_GetVoterByLastQuarter_Result
    {
        public int VoteID { get; set; }
        public Nullable<decimal> Vote { get; set; }
        public Nullable<int> BrokerID { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> DelStatus { get; set; }
        public Nullable<int> MaxLimit { get; set; }
        public string BrokerName { get; set; }
        public string AnalystName { get; set; }
        public Nullable<int> GradingID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string SectorName { get; set; }
        public string EmpID { get; set; }
    }
}
