//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    
    public partial class BGS_GetGradingMaster_Result
    {
        public string UserName { get; set; }
        public string Department { get; set; }
        public string RoleName { get; set; }
        public string EmailID { get; set; }
        public string StatusName { get; set; }
        public bool IsConfirm { get; set; }
        public bool IsSend { get; set; }
        public Nullable<int> GradingID { get; set; }
        public string EmpID { get; set; }
    }
}
