//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ID { get; set; }
        public string PAGE_NAME { get; set; }
        public string ERROR_CODE { get; set; }
        public string ERROR_DETAIL { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string Created_By { get; set; }
    }
}
