//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOD_DOFAReason
    {
        public DOD_DOFAReason()
        {
            this.VoteMasters = new HashSet<VoteMaster>();
        }
    
        public int ReasonID { get; set; }
        public string ReasonName { get; set; }
    
        public virtual ICollection<VoteMaster> VoteMasters { get; set; }
    }
}
