//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuarterMaster
    {
        public QuarterMaster()
        {
            this.GradingMasters = new HashSet<GradingMaster>();
            this.RankMasters = new HashSet<RankMaster>();
            this.BrokerConfigs = new HashSet<BrokerConfig>();
        }
    
        public int QuarterID { get; set; }
        public string Name { get; set; }
        public Nullable<int> QuarterYear { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> DelStatus { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<GradingMaster> GradingMasters { get; set; }
        public virtual ICollection<RankMaster> RankMasters { get; set; }
        public virtual ICollection<BrokerConfig> BrokerConfigs { get; set; }
    }
}
