//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    
    public partial class GetMenuItem_Employee_Result
    {
        public string ModuleName { get; set; }
        public string ScreenName { get; set; }
        public string URL { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> ScreenId { get; set; }
    }
}
