//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerAnalyst
    {
        public int BrokerAnalystId { get; set; }
        public int BrokerID { get; set; }
        public string EmpID { get; set; }
        public Nullable<int> VoteID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> DelStatus { get; set; }
    
        public virtual StatusMaster StatusMaster { get; set; }
    }
}
