//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    
    public partial class BGS_GetVoterByCurrentQuarter_Result
    {
        public Nullable<int> SectorID { get; set; }
        public int VoteID { get; set; }
        public Nullable<decimal> Vote { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<int> BrokerID { get; set; }
        public Nullable<int> MaxLimit { get; set; }
        public string BrokerName { get; set; }
        public Nullable<int> BrokerNameID { get; set; }
        public string AnalystName { get; set; }
        public Nullable<int> GradingID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string SectorName { get; set; }
        public string EmpID { get; set; }
        public string RoleName { get; set; }
        public string Name { get; set; }
    }
}
