//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerConfig
    {
        public int BrokerConfigId { get; set; }
        public int QuarterId { get; set; }
        public Nullable<bool> IsEmailSend { get; set; }
        public int BrokerNameId { get; set; }
    
        public virtual BrokerNameMaster BrokerNameMaster { get; set; }
        public virtual QuarterMaster QuarterMaster { get; set; }
    }
}
