//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerNameMaster
    {
        public BrokerNameMaster()
        {
            this.BrokerMasters = new HashSet<BrokerMaster>();
            this.RankMasters = new HashSet<RankMaster>();
            this.UserMasters = new HashSet<UserMaster>();
            this.VoteMasters = new HashSet<VoteMaster>();
            this.BrokerConfigs = new HashSet<BrokerConfig>();
        }
    
        public int BrokerNameID { get; set; }
        public string BrokerName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> DelStatus { get; set; }
        public Nullable<int> MaxLimit { get; set; }
        public Nullable<bool> EmailStatus { get; set; }
        public Nullable<int> Broker_DofaCode { get; set; }
    
        public virtual ICollection<BrokerMaster> BrokerMasters { get; set; }
        public virtual ICollection<RankMaster> RankMasters { get; set; }
        public virtual ICollection<UserMaster> UserMasters { get; set; }
        public virtual ICollection<VoteMaster> VoteMasters { get; set; }
        public virtual ICollection<BrokerConfig> BrokerConfigs { get; set; }
    }
}
