//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerMaster
    {
        public int BrokerID { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<int> BrokerTypeID { get; set; }
        public string Name { get; set; }
        public string EmailID { get; set; }
        public string Number { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> DelStatus { get; set; }
        public Nullable<int> BrokerNameID { get; set; }
    
        public virtual BrokerMaster BrokerMaster1 { get; set; }
        public virtual BrokerMaster BrokerMaster2 { get; set; }
        public virtual BrokerTypeMaster BrokerTypeMaster { get; set; }
        public virtual BrokerNameMaster BrokerNameMaster { get; set; }
    }
}
