//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleMaster
    {
        public ModuleMaster()
        {
            this.ScreenAssignDetails = new HashSet<ScreenAssignDetail>();
            this.ScreenMasters = new HashSet<ScreenMaster>();
        }
    
        public int ModuleID { get; set; }
        public string ModuleName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string DelStatus { get; set; }
    
        public virtual ICollection<ScreenAssignDetail> ScreenAssignDetails { get; set; }
        public virtual ICollection<ScreenMaster> ScreenMasters { get; set; }
    }
}
