//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenAssignDetail
    {
        public int ScreenAssignId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> ScreenId { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> DelStatus { get; set; }
    
        public virtual ModuleMaster ModuleMaster { get; set; }
        public virtual ScreenMaster ScreenMaster { get; set; }
    }
}
