//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EmpID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string EmailID { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<bool> Isforce { get; set; }
        public Nullable<bool> IsUTI { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> DelStatus { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<int> BrokerNameID { get; set; }
    
        public virtual BrokerNameMaster BrokerNameMaster { get; set; }
        public virtual DepartmentMaster DepartmentMaster { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
        public virtual UserMaster UserMaster2 { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
