//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;

    public partial class BGSEntities : DbContext
    {
        public BGSEntities()
            : base("name=BGSEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<BrokerAnalyst> BrokerAnalysts { get; set; }
        public DbSet<BrokerMaster> BrokerMasters { get; set; }
        public DbSet<BrokerNameMaster> BrokerNameMasters { get; set; }
        public DbSet<BrokerTypeMaster> BrokerTypeMasters { get; set; }
        public DbSet<DepartmentMaster> DepartmentMasters { get; set; }
        public DbSet<ErrorLog> ErrorLogs { get; set; }
        public DbSet<GradingMaster> GradingMasters { get; set; }
        public DbSet<GradingMaster_Archive> GradingMaster_Archive { get; set; }
        public DbSet<ModuleMaster> ModuleMasters { get; set; }
        public DbSet<QuarterMaster> QuarterMasters { get; set; }
        public DbSet<RankMaster> RankMasters { get; set; }
        public DbSet<RoleMaster> RoleMasters { get; set; }
        public DbSet<ScreenAssignDetail> ScreenAssignDetails { get; set; }
        public DbSet<ScreenMaster> ScreenMasters { get; set; }
        public DbSet<SectorMaster> SectorMasters { get; set; }
        public DbSet<StatusMaster> StatusMasters { get; set; }
        public DbSet<UserMaster> UserMasters { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<VoteMaster> VoteMasters { get; set; }
        public DbSet<WeightMaster> WeightMasters { get; set; }
        public DbSet<BrokerConfig> BrokerConfigs { get; set; }

        public virtual ObjectResult<Nullable<int>> AuthenticateDublicateVoter(string brokerName, string analystName, Nullable<int> sectorID, string empID)
        {
            var brokerNameParameter = brokerName != null ?
                new ObjectParameter("BrokerName", brokerName) :
                new ObjectParameter("BrokerName", typeof(string));

            var analystNameParameter = analystName != null ?
                new ObjectParameter("AnalystName", analystName) :
                new ObjectParameter("AnalystName", typeof(string));

            var sectorIDParameter = sectorID.HasValue ?
                new ObjectParameter("SectorID", sectorID) :
                new ObjectParameter("SectorID", typeof(int));

            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("AuthenticateDublicateVoter", brokerNameParameter, analystNameParameter, sectorIDParameter, empIDParameter);
        }

        public virtual ObjectResult<BGD_GetBrokerNameMaster_Result> BGD_GetBrokerNameMaster(string empID)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGD_GetBrokerNameMaster_Result>("BGD_GetBrokerNameMaster", empIDParameter);
        }

        public virtual int BGS_AssignScreen_linking(string employeeId)
        {
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_AssignScreen_linking", employeeIdParameter);
        }

        public virtual int BGS_AssignScreenToUser(Nullable<int> sCREENID, Nullable<int> mODULEID, string eMPLOYEEID, Nullable<int> sCREENASSIGNID, string cREATEDBY, Nullable<bool> aCTIVE)
        {
            var sCREENIDParameter = sCREENID.HasValue ?
                new ObjectParameter("SCREENID", sCREENID) :
                new ObjectParameter("SCREENID", typeof(int));

            var mODULEIDParameter = mODULEID.HasValue ?
                new ObjectParameter("MODULEID", mODULEID) :
                new ObjectParameter("MODULEID", typeof(int));

            var eMPLOYEEIDParameter = eMPLOYEEID != null ?
                new ObjectParameter("EMPLOYEEID", eMPLOYEEID) :
                new ObjectParameter("EMPLOYEEID", typeof(string));

            var sCREENASSIGNIDParameter = sCREENASSIGNID.HasValue ?
                new ObjectParameter("SCREENASSIGNID", sCREENASSIGNID) :
                new ObjectParameter("SCREENASSIGNID", typeof(int));

            var cREATEDBYParameter = cREATEDBY != null ?
                new ObjectParameter("CREATEDBY", cREATEDBY) :
                new ObjectParameter("CREATEDBY", typeof(string));

            var aCTIVEParameter = aCTIVE.HasValue ?
                new ObjectParameter("ACTIVE", aCTIVE) :
                new ObjectParameter("ACTIVE", typeof(bool));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_AssignScreenToUser", sCREENIDParameter, mODULEIDParameter, eMPLOYEEIDParameter, sCREENASSIGNIDParameter, cREATEDBYParameter, aCTIVEParameter);
        }

        public virtual ObjectResult<Nullable<int>> BGS_AuthenticateBrokerMaster(Nullable<int> brokerNameID, Nullable<int> brokerTypeID, string analystName, Nullable<int> sectorID, Nullable<int> brokerID)
        {
            var brokerNameIDParameter = brokerNameID.HasValue ?
                new ObjectParameter("BrokerNameID", brokerNameID) :
                new ObjectParameter("BrokerNameID", typeof(int));

            var brokerTypeIDParameter = brokerTypeID.HasValue ?
                new ObjectParameter("BrokerTypeID", brokerTypeID) :
                new ObjectParameter("BrokerTypeID", typeof(int));

            var analystNameParameter = analystName != null ?
                new ObjectParameter("AnalystName", analystName) :
                new ObjectParameter("AnalystName", typeof(string));

            var sectorIDParameter = sectorID.HasValue ?
                new ObjectParameter("SectorID", sectorID) :
                new ObjectParameter("SectorID", typeof(int));

            var brokerIDParameter = brokerID.HasValue ?
                new ObjectParameter("BrokerID", brokerID) :
                new ObjectParameter("BrokerID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("BGS_AuthenticateBrokerMaster", brokerNameIDParameter, brokerTypeIDParameter, analystNameParameter, sectorIDParameter, brokerIDParameter);
        }

        public virtual ObjectResult<Nullable<int>> BGS_AuthenticateGrading()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("BGS_AuthenticateGrading");
        }

        public virtual ObjectResult<BGS_BindBrokerName_Result> BGS_BindBrokerName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_BindBrokerName_Result>("BGS_BindBrokerName");
        }

        public virtual ObjectResult<BGS_BindQuarter_Result> BGS_BindQuarter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_BindQuarter_Result>("BGS_BindQuarter");
        }

        public virtual ObjectResult<BGS_BindSectorMaster_Result> BGS_BindSectorMaster()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_BindSectorMaster_Result>("BGS_BindSectorMaster");
        }

        public virtual int BGS_BindUserMaster(string userName, string type)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));

            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_BindUserMaster", userNameParameter, typeParameter);
        }

        public virtual ObjectResult<BGS_BindVoter_Result> BGS_BindVoter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_BindVoter_Result>("BGS_BindVoter");
        }

        public virtual int BGS_BrokerMaster(string transType, Nullable<int> brokerID, Nullable<int> sectorID, Nullable<int> brokerTypeID, string name, string number, string emailID, string createdBy, string updatedBy, Nullable<int> brokerNameID)
        {
            var transTypeParameter = transType != null ?
                new ObjectParameter("TransType", transType) :
                new ObjectParameter("TransType", typeof(string));

            var brokerIDParameter = brokerID.HasValue ?
                new ObjectParameter("BrokerID", brokerID) :
                new ObjectParameter("BrokerID", typeof(int));

            var sectorIDParameter = sectorID.HasValue ?
                new ObjectParameter("SectorID", sectorID) :
                new ObjectParameter("SectorID", typeof(int));

            var brokerTypeIDParameter = brokerTypeID.HasValue ?
                new ObjectParameter("BrokerTypeID", brokerTypeID) :
                new ObjectParameter("BrokerTypeID", typeof(int));

            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));

            var numberParameter = number != null ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(string));

            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));

            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));

            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));

            var brokerNameIDParameter = brokerNameID.HasValue ?
                new ObjectParameter("BrokerNameID", brokerNameID) :
                new ObjectParameter("BrokerNameID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_BrokerMaster", transTypeParameter, brokerIDParameter, sectorIDParameter, brokerTypeIDParameter, nameParameter, numberParameter, emailIDParameter, createdByParameter, updatedByParameter, brokerNameIDParameter);
        }
        //public virtual int BGS_InsertUpdateFirmMaster(Nullable<int> FirmID, string FirmName, string CreatedBy, Nullable<DateTime> CreatedOn, string UpdatedBy, Nullable<DateTime> UpdatedOn, Nullable<bool> DelStatus, Nullable<int> MaxLimit, Nullable<bool> EmailStatus, Nullable<int> DofaCode)
        //{
        //    var FirmParameter = FirmID.HasValue ?
        //        new ObjectParameter("FirmID", FirmID) :
        //        new ObjectParameter("FirmID", typeof(int));

        //    var FirmNameParameter = FirmName!=null ?
        //        new ObjectParameter("FirmName", FirmName) :
        //        new ObjectParameter("FirmName", typeof(string));

        //    var CreatedByParameter = CreatedBy!=null ?
        //        new ObjectParameter("CreatedBy", CreatedBy) :
        //        new ObjectParameter("CreatedBy", typeof(string));

        //    var CreatedOnParameter = CreatedOn.HasValue ?
        //        new ObjectParameter("CreatedOn", CreatedOn) :
        //        new ObjectParameter("CreatedOn", typeof(DateTime));

        //    var UpdatedByParameter = UpdatedBy!=null ?
        //       new ObjectParameter("UpdatedBy", UpdatedBy) :
        //       new ObjectParameter("UpdatedBy", typeof(string));

        //    var UpdatedOnParameter = UpdatedOn.HasValue ?
        //        new ObjectParameter("UpdatedOn", UpdatedOn) :
        //        new ObjectParameter("UpdatedOn", typeof(DateTime));

        //    var DelStatusParameter = DelStatus.HasValue?
        //        new ObjectParameter("DelStatus", DelStatus) :
        //        new ObjectParameter("DelStatus", typeof(bool));

        //    var MaxLimitParameter = MaxLimit.HasValue ?
        //        new ObjectParameter("MaxLimit", MaxLimit) :
        //        new ObjectParameter("MaxLimit", typeof(int));

        //    var EmailStatusParameter = EmailStatus != null ?
        //        new ObjectParameter("EmailStatus", EmailStatus) :
        //        new ObjectParameter("EmailStatus", typeof(bool));

        //    var DofaCodeParameter = DofaCode != null ?
        //        new ObjectParameter("Broker_DofaCodee", DofaCode) :
        //        new ObjectParameter("Broker_DofaCode", typeof(string));

        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_InsertUpdateFirmMaster", FirmParameter, FirmNameParameter, CreatedByParameter, CreatedOnParameter, UpdatedByParameter, UpdatedOnParameter, MaxLimitParameter, EmailStatusParameter, DofaCodeParameter);
        //}
        public virtual ObjectResult<BGS_CalculateRank_Result> BGS_CalculateRank(Nullable<int> quarterID)
        {
            var quarterIDParameter = quarterID.HasValue ?
                new ObjectParameter("QuarterID", quarterID) :
                new ObjectParameter("QuarterID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_CalculateRank_Result>("BGS_CalculateRank", quarterIDParameter);
        }

        public virtual int BGS_ChangePassword(string empId, string oldPassword, string newPassword, ObjectParameter message)
        {
            var empIdParameter = empId != null ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(string));

            var oldPasswordParameter = oldPassword != null ?
                new ObjectParameter("OldPassword", oldPassword) :
                new ObjectParameter("OldPassword", typeof(string));

            var newPasswordParameter = newPassword != null ?
                new ObjectParameter("NewPassword", newPassword) :
                new ObjectParameter("NewPassword", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_ChangePassword", empIdParameter, oldPasswordParameter, newPasswordParameter, message);
        }

        public virtual ObjectResult<Nullable<int>> BGS_CheckRankInsert(Nullable<int> quarter)
        {
            var quarterParameter = quarter.HasValue ?
                new ObjectParameter("quarter", quarter) :
                new ObjectParameter("quarter", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("BGS_CheckRankInsert", quarterParameter);
        }

        public virtual int BGS_CheckUtiUser(string empID, ObjectParameter bIT)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_CheckUtiUser", empIDParameter, bIT);
        }

        public virtual ObjectResult<Nullable<int>> BGS_DeleteBrokerMaster(Nullable<int> brokerId)
        {
            var brokerIdParameter = brokerId.HasValue ?
                new ObjectParameter("BrokerId", brokerId) :
                new ObjectParameter("BrokerId", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("BGS_DeleteBrokerMaster", brokerIdParameter);
        }

        public virtual int BGS_DeleteQuarterMaster(Nullable<int> quarterID)
        {
            var quarterIDParameter = quarterID.HasValue ?
                new ObjectParameter("QuarterID", quarterID) :
                new ObjectParameter("QuarterID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_DeleteQuarterMaster", quarterIDParameter);
        }

        public virtual int BGS_DeleteUsers(Nullable<int> uSERID)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_DeleteUsers", uSERIDParameter);
        }

        public virtual int BGS_DeleteVoteMaster(Nullable<int> voteID, string empID)
        {
            var voteIDParameter = voteID.HasValue ?
                new ObjectParameter("VoteID", voteID) :
                new ObjectParameter("VoteID", typeof(int));

            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_DeleteVoteMaster", voteIDParameter, empIDParameter);
        }

        public virtual ObjectResult<string> BGS_GetAnalystName(string prefix)
        {
            var prefixParameter = prefix != null ?
                new ObjectParameter("Prefix", prefix) :
                new ObjectParameter("Prefix", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BGS_GetAnalystName", prefixParameter);
        }

        public virtual ObjectResult<BGS_GetAsssignScreens_Result> BGS_GetAsssignScreens(string eMPID)
        {
            var eMPIDParameter = eMPID != null ?
                new ObjectParameter("EMPID", eMPID) :
                new ObjectParameter("EMPID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetAsssignScreens_Result>("BGS_GetAsssignScreens", eMPIDParameter);
        }

        public virtual ObjectResult<Nullable<int>> BGS_GetBokerNameID(string brokerName)
        {
            var brokerNameParameter = brokerName != null ?
                new ObjectParameter("BrokerName", brokerName) :
                new ObjectParameter("BrokerName", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("BGS_GetBokerNameID", brokerNameParameter);
        }

        public virtual ObjectResult<string> BGS_GetBrokerAnalyst(string brokerName)
        {
            var brokerNameParameter = brokerName != null ?
                new ObjectParameter("BrokerName", brokerName) :
                new ObjectParameter("BrokerName", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BGS_GetBrokerAnalyst", brokerNameParameter);
        }

        public virtual ObjectResult<BGS_GetBrokerDetailsByBrokerNameBrokerAnalyst_Result> BGS_GetBrokerDetailsByBrokerNameBrokerAnalyst(string brokerName, string name, string empID)
        {
            var brokerNameParameter = brokerName != null ?
                new ObjectParameter("BrokerName", brokerName) :
                new ObjectParameter("BrokerName", typeof(string));

            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));

            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetBrokerDetailsByBrokerNameBrokerAnalyst_Result>("BGS_GetBrokerDetailsByBrokerNameBrokerAnalyst", brokerNameParameter, nameParameter, empIDParameter);
        }

        public virtual ObjectResult<Nullable<int>> BGS_GetBrokerId(string brokerName)
        {
            var brokerNameParameter = brokerName != null ?
                new ObjectParameter("BrokerName", brokerName) :
                new ObjectParameter("BrokerName", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("BGS_GetBrokerId", brokerNameParameter);
        }

        public virtual ObjectResult<BGS_GetBrokerMaster_Result> BGS_GetBrokerMaster(string empID, string brokerNameSearch)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            var brokerNameSearchParameter = brokerNameSearch != null ?
                new ObjectParameter("BrokerNameSearch", brokerNameSearch) :
                new ObjectParameter("BrokerNameSearch", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetBrokerMaster_Result>("BGS_GetBrokerMaster", empIDParameter, brokerNameSearchParameter);
        }

        public virtual ObjectResult<Nullable<int>> BGS_GetBrokerMaxLimit(string brokerName)
        {
            var brokerNameParameter = brokerName != null ?
                new ObjectParameter("BrokerName", brokerName) :
                new ObjectParameter("BrokerName", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("BGS_GetBrokerMaxLimit", brokerNameParameter);
        }

        public virtual ObjectResult<BGS_GetBrokerName_Result> BGS_GetBrokerName(string prefix)
        {
            var prefixParameter = prefix != null ?
                new ObjectParameter("prefix", prefix) :
                new ObjectParameter("prefix", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetBrokerName_Result>("BGS_GetBrokerName", prefixParameter);
        }
        public virtual ObjectResult<BGS_GetDOD_DOFAReason_Result1> BGS_GetDOD_DOFAReason(string prefix)
        {
            var prefixParameter = prefix != null ?
                new ObjectParameter("prefix", prefix) :
                new ObjectParameter("prefix", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetDOD_DOFAReason_Result1>("BGS_GetDOD_DOFAReason", prefixParameter);
        }

        public virtual ObjectResult<BGS_GetBrokerNameForBrokerMster_Result> BGS_GetBrokerNameForBrokerMster(string prefix)
        {
            var prefixParameter = prefix != null ?
                new ObjectParameter("prefix", prefix) :
                new ObjectParameter("prefix", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetBrokerNameForBrokerMster_Result>("BGS_GetBrokerNameForBrokerMster", prefixParameter);
        }

        public virtual int BGS_GetBrokerOrFirmName(string brokeSerach)
        {
            var brokeSerachParameter = brokeSerach != null ?
                new ObjectParameter("BrokeSerach", brokeSerach) :
                new ObjectParameter("BrokeSerach", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_GetBrokerOrFirmName", brokeSerachParameter);
        }

        public virtual ObjectResult<BGS_GetBrokerRanking_Result> BGS_GetBrokerRanking()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetBrokerRanking_Result>("BGS_GetBrokerRanking");
        }

        public virtual int BGS_GetBrokerReportByCurrentQuarter(Nullable<int> quarterID, string brokerName)
        {
            var quarterIDParameter = quarterID.HasValue ?
                new ObjectParameter("QuarterID", quarterID) :
                new ObjectParameter("QuarterID", typeof(int));

            var brokerNameParameter = brokerName != null ?
                new ObjectParameter("BrokerName", brokerName) :
                new ObjectParameter("BrokerName", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_GetBrokerReportByCurrentQuarter", quarterIDParameter, brokerNameParameter);
        }

        public virtual int BGS_GetBrokerReportByLastQuarter(Nullable<int> quarterID, string brokerName)
        {
            var quarterIDParameter = quarterID.HasValue ?
                new ObjectParameter("QuarterID", quarterID) :
                new ObjectParameter("QuarterID", typeof(int));

            var brokerNameParameter = brokerName != null ?
                new ObjectParameter("BrokerName", brokerName) :
                new ObjectParameter("BrokerName", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_GetBrokerReportByLastQuarter", quarterIDParameter, brokerNameParameter);
        }

        public virtual ObjectResult<BGS_GetBrokerTypeMasterData_Result> BGS_GetBrokerTypeMasterData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetBrokerTypeMasterData_Result>("BGS_GetBrokerTypeMasterData");
        }

        public virtual int BGS_GetBrokerWiseQuarterRank(Nullable<int> quarterID)
        {
            var quarterIDParameter = quarterID.HasValue ?
                new ObjectParameter("QuarterID", quarterID) :
                new ObjectParameter("QuarterID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_GetBrokerWiseQuarterRank", quarterIDParameter);
        }

        public virtual ObjectResult<BGS_GetCuurentQuarterVoterStatus_Result> BGS_GetCuurentQuarterVoterStatus(Nullable<int> quarterID)
        {
            var quarterIDParameter = quarterID.HasValue ?
                new ObjectParameter("quarterID", quarterID) :
                new ObjectParameter("quarterID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetCuurentQuarterVoterStatus_Result>("BGS_GetCuurentQuarterVoterStatus", quarterIDParameter);
        }

        public virtual ObjectResult<BGS_GetEmailListing_Result> BGS_GetEmailListing(Nullable<int> quarterID)
        {
            var quarterIDParameter = quarterID.HasValue ?
                new ObjectParameter("QuarterID", quarterID) :
                new ObjectParameter("QuarterID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetEmailListing_Result>("BGS_GetEmailListing", quarterIDParameter);
        }
        public virtual ObjectResult<BGS_GetEmailListing_Result> ExcelListing(Nullable<int> quarterID)
        {
            var quarterIDParameter = quarterID.HasValue ?
                new ObjectParameter("QuarterID", quarterID) :
                new ObjectParameter("QuarterID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetEmailListing_Result>("BGS_GetEmailListing", quarterIDParameter);
        }

        public virtual int BGS_GetError(string page, string errorCode, string errorDetail, string date, string created_By)
        {
            var pageParameter = page != null ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(string));

            var errorCodeParameter = errorCode != null ?
                new ObjectParameter("ErrorCode", errorCode) :
                new ObjectParameter("ErrorCode", typeof(string));

            var errorDetailParameter = errorDetail != null ?
                new ObjectParameter("ErrorDetail", errorDetail) :
                new ObjectParameter("ErrorDetail", typeof(string));

            var dateParameter = date != null ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(string));

            var created_ByParameter = created_By != null ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_GetError", pageParameter, errorCodeParameter, errorDetailParameter, dateParameter, created_ByParameter);
        }

        public virtual ObjectResult<BGS_GetGradingMaster_Result> BGS_GetGradingMaster(string deptID)
        {
            var deptIDParameter = deptID != null ?
                new ObjectParameter("DeptID", deptID) :
                new ObjectParameter("DeptID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetGradingMaster_Result>("BGS_GetGradingMaster", deptIDParameter);
        }

        //public virtual ObjectResult<BGS_GetGradingMaster_Result> BGS_GetGradingMaster_NEW(string deptID)
        //{
        //    var deptIDParameter = deptID != null ?
        //        new ObjectParameter("DeptID", deptID) :
        //        new ObjectParameter("DeptID", typeof(string));

        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetGradingMaster_Result>("BGS_GetGradingMaster", deptIDParameter);
        //}

        public virtual ObjectResult<BGS_GetLastQuarterNameById_Result> BGS_GetLastQuarterNameById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetLastQuarterNameById_Result>("BGS_GetLastQuarterNameById", idParameter);
        }

        public virtual ObjectResult<BGS_GetPerBrokerRankStatus_Result> BGS_GetPerBrokerRankStatus(Nullable<int> brokerNameID, Nullable<int> quarterID)
        {
            var brokerNameIDParameter = brokerNameID.HasValue ?
                new ObjectParameter("BrokerNameID", brokerNameID) :
                new ObjectParameter("BrokerNameID", typeof(int));

            var quarterIDParameter = quarterID.HasValue ?
                new ObjectParameter("QuarterID", quarterID) :
                new ObjectParameter("QuarterID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetPerBrokerRankStatus_Result>("BGS_GetPerBrokerRankStatus", brokerNameIDParameter, quarterIDParameter);
        }

        public virtual ObjectResult<BGS_GetQuarterMaster_Result> BGS_GetQuarterMaster()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetQuarterMaster_Result>("BGS_GetQuarterMaster");
        }

        public virtual ObjectResult<BGS_GetQuarterName_Result> BGS_GetQuarterName(string prefix)
        {
            var prefixParameter = prefix != null ?
                new ObjectParameter("Prefix", prefix) :
                new ObjectParameter("Prefix", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetQuarterName_Result>("BGS_GetQuarterName", prefixParameter);
        }

        public virtual ObjectResult<BGS_GetQuarterNameById_Result> BGS_GetQuarterNameById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetQuarterNameById_Result>("BGS_GetQuarterNameById", idParameter);
        }
        public virtual ObjectResult<BGS_GetQuarterNameById_Result> BGS_GetQuarterName2ById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetQuarterNameById_Result>("BGS_GetQuarterName2ById", idParameter);
        }

        public virtual ObjectResult<BGS_GetQuarterNameDuteDate_Result> BGS_GetQuarterNameDuteDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetQuarterNameDuteDate_Result>("BGS_GetQuarterNameDuteDate");
        }

        public virtual int BGS_GetQuarterWiseBrokerReport(Nullable<int> quarterID, string voterName, string sectorName, string brokerName)
        {
            var quarterIDParameter = quarterID.HasValue ?
                new ObjectParameter("QuarterID", quarterID) :
                new ObjectParameter("QuarterID", typeof(int));

            var voterNameParameter = voterName != null ?
                new ObjectParameter("VoterName", voterName) :
                new ObjectParameter("VoterName", typeof(string));

            var sectorNameParameter = sectorName != null ?
                new ObjectParameter("SectorName", sectorName) :
                new ObjectParameter("SectorName", typeof(string));

            var brokerNameParameter = brokerName != null ?
                new ObjectParameter("BrokerName", brokerName) :
                new ObjectParameter("BrokerName", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_GetQuarterWiseBrokerReport", quarterIDParameter, voterNameParameter, sectorNameParameter, brokerNameParameter);
        }

        public virtual ObjectResult<BGS_GetRABrokerName_Result> BGS_GetRABrokerName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetRABrokerName_Result>("BGS_GetRABrokerName");
        }

        public virtual ObjectResult<BGS_GetRoleDeptDetails_Result> BGS_GetRoleDeptDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetRoleDeptDetails_Result>("BGS_GetRoleDeptDetails");
        }

        public virtual ObjectResult<BGS_GetSector_Result> BGS_GetSector()
                       {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetSector_Result>("BGS_GetSector");
        }

        public virtual int BGS_GetSectorWiseBrokerData(Nullable<int> sectorId)
        {
            var sectorIdParameter = sectorId.HasValue ?
                new ObjectParameter("SectorId", sectorId) :
                new ObjectParameter("SectorId", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_GetSectorWiseBrokerData", sectorIdParameter);
        }

        public virtual ObjectResult<BGS_GetUser_Result> BGS_GetUser(string empID, string password)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetUser_Result>("BGS_GetUser", empIDParameter, passwordParameter);
        }

        public virtual ObjectResult<BGS_GetUserDetails_Result> BGS_GetUserDetails(string eMPID)
        {
            var eMPIDParameter = eMPID != null ?
                new ObjectParameter("EMPID", eMPID) :
                new ObjectParameter("EMPID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetUserDetails_Result>("BGS_GetUserDetails", eMPIDParameter);
        }

        public virtual ObjectResult<BGS_GetUserDetailsForVoter_Result> BGS_GetUserDetailsForVoter(string empID)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetUserDetailsForVoter_Result>("BGS_GetUserDetailsForVoter", empIDParameter);
        }

        public virtual ObjectResult<BGS_GetUserTypes_Result> BGS_GetUserTypes(string lOGINTYPE)
        {
            var lOGINTYPEParameter = lOGINTYPE != null ?
                new ObjectParameter("LOGINTYPE", lOGINTYPE) :
                new ObjectParameter("LOGINTYPE", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetUserTypes_Result>("BGS_GetUserTypes", lOGINTYPEParameter);
        }

        public virtual ObjectResult<BGS_GetVoterByCurrentQuarter_Result> BGS_GetVoterByCurrentQuarter(string empID)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetVoterByCurrentQuarter_Result>("BGS_GetVoterByCurrentQuarter", empIDParameter);
        }

        public virtual ObjectResult<BGS_GetVoterByLastQuarter_Result> BGS_GetVoterByLastQuarter(string empID)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetVoterByLastQuarter_Result>("BGS_GetVoterByLastQuarter", empIDParameter);
        }

        public virtual ObjectResult<BGS_GetVoterName_Result> BGS_GetVoterName(string empID)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetVoterName_Result>("BGS_GetVoterName", empIDParameter);
        }

        public virtual ObjectResult<BGS_GetVoterSector_Result> BGS_GetVoterSector(Nullable<int> brokerNameID, string analystName)
        {
            var brokerNameIDParameter = brokerNameID.HasValue ?
                new ObjectParameter("BrokerNameID", brokerNameID) :
                new ObjectParameter("BrokerNameID", typeof(int));

            var analystNameParameter = analystName != null ?
                new ObjectParameter("AnalystName", analystName) :
                new ObjectParameter("AnalystName", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetVoterSector_Result>("BGS_GetVoterSector", brokerNameIDParameter, analystNameParameter);
        }

        public virtual int BGS_GetWeightMaster()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_GetWeightMaster");
        }

        public virtual int BGS_InsertNewQuarterGrading(string quarterName, Nullable<System.DateTime> qurterDueDate, Nullable<System.DateTime> qurterStartDate, Nullable<System.DateTime> qurterEndDate)
        {
            var quarterNameParameter = quarterName != null ?
                new ObjectParameter("QuarterName", quarterName) :
                new ObjectParameter("QuarterName", typeof(string));

            var qurterDueDateParameter = qurterDueDate.HasValue ?
                new ObjectParameter("QurterDueDate", qurterDueDate) :
                new ObjectParameter("QurterDueDate", typeof(System.DateTime));

            var qurterStartDateParameter = qurterStartDate.HasValue ?
               new ObjectParameter("QurterStartDate", qurterStartDate) :
               new ObjectParameter("QurterStartDate", typeof(System.DateTime));

            var qurterEndDateParameter = qurterEndDate.HasValue ?
               new ObjectParameter("QurterEndDate", qurterEndDate) :
               new ObjectParameter("QurterEndDate", typeof(System.DateTime));


            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_InsertNewQuarterGrading", quarterNameParameter, qurterDueDateParameter, qurterStartDateParameter, qurterEndDateParameter);
        }

        public virtual int BGS_InsertRank(Nullable<int> brokerNameID, Nullable<int> quarterID, Nullable<int> voteID, Nullable<int> maxLimit, Nullable<int> rank, string createdBy, Nullable<double> totalScore)
        {
            var brokerNameIDParameter = brokerNameID.HasValue ?
                new ObjectParameter("BrokerNameID", brokerNameID) :
                new ObjectParameter("BrokerNameID", typeof(int));

            var quarterIDParameter = quarterID.HasValue ?
                new ObjectParameter("QuarterID", quarterID) :
                new ObjectParameter("QuarterID", typeof(int));

            var voteIDParameter = voteID.HasValue ?
                new ObjectParameter("VoteID", voteID) :
                new ObjectParameter("VoteID", typeof(int));

            var maxLimitParameter = maxLimit.HasValue ?
                new ObjectParameter("MaxLimit", maxLimit) :
                new ObjectParameter("MaxLimit", typeof(int));

            var rankParameter = rank.HasValue ?
                new ObjectParameter("Rank", rank) :
                new ObjectParameter("Rank", typeof(int));

            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));

            var totalScoreParameter = totalScore.HasValue ?
                new ObjectParameter("totalScore", totalScore) :
                new ObjectParameter("totalScore", typeof(double));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_InsertRank", brokerNameIDParameter, quarterIDParameter, voteIDParameter, maxLimitParameter, rankParameter, createdByParameter, totalScoreParameter);
        }

        public virtual int BGS_InsertUpdateUsers(string eMPLOYEEID, string uSERPWD, Nullable<int> rOLEID, Nullable<int> dEPTID, Nullable<bool> iSACITVE, string eMAILID, string nAME, Nullable<bool> iSFORCE, Nullable<bool> iSUTI, string cREATEDBY, Nullable<double> wEIGHT, Nullable<int> uSERTYPE, string brokerName, Nullable<int> maxLimit)
        {
            var eMPLOYEEIDParameter = eMPLOYEEID != null ?
                new ObjectParameter("EMPLOYEEID", eMPLOYEEID) :
                new ObjectParameter("EMPLOYEEID", typeof(string));

            var uSERPWDParameter = uSERPWD != null ?
                new ObjectParameter("USERPWD", uSERPWD) :
                new ObjectParameter("USERPWD", typeof(string));

            var rOLEIDParameter = rOLEID.HasValue ?
                new ObjectParameter("ROLEID", rOLEID) :
                new ObjectParameter("ROLEID", typeof(int));

            var dEPTIDParameter = dEPTID.HasValue ?
                new ObjectParameter("DEPTID", dEPTID) :
                new ObjectParameter("DEPTID", typeof(int));

            var iSACITVEParameter = iSACITVE.HasValue ?
                new ObjectParameter("ISACITVE", iSACITVE) :
                new ObjectParameter("ISACITVE", typeof(bool));

            var eMAILIDParameter = eMAILID != null ?
                new ObjectParameter("EMAILID", eMAILID) :
                new ObjectParameter("EMAILID", typeof(string));

            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));

            var iSFORCEParameter = iSFORCE.HasValue ?
                new ObjectParameter("ISFORCE", iSFORCE) :
                new ObjectParameter("ISFORCE", typeof(bool));

            var iSUTIParameter = iSUTI.HasValue ?
                new ObjectParameter("ISUTI", iSUTI) :
                new ObjectParameter("ISUTI", typeof(bool));

            var cREATEDBYParameter = cREATEDBY != null ?
                new ObjectParameter("CREATEDBY", cREATEDBY) :
                new ObjectParameter("CREATEDBY", typeof(string));

            var wEIGHTParameter = wEIGHT.HasValue ?
                new ObjectParameter("WEIGHT", wEIGHT) :
                new ObjectParameter("WEIGHT", typeof(double));

            var uSERTYPEParameter = uSERTYPE.HasValue ?
                new ObjectParameter("USERTYPE", uSERTYPE) :
                new ObjectParameter("USERTYPE", typeof(int));

            var brokerNameParameter = brokerName != null ?
                new ObjectParameter("BrokerName", brokerName) :
                new ObjectParameter("BrokerName", typeof(string));

            var maxLimitParameter = maxLimit.HasValue ?
                new ObjectParameter("MaxLimit", maxLimit) :
                new ObjectParameter("MaxLimit", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_InsertUpdateUsers", eMPLOYEEIDParameter, uSERPWDParameter, rOLEIDParameter, dEPTIDParameter, iSACITVEParameter, eMAILIDParameter, nAMEParameter, iSFORCEParameter, iSUTIParameter, cREATEDBYParameter, wEIGHTParameter, uSERTYPEParameter, brokerNameParameter, maxLimitParameter);
        }

        public virtual ObjectResult<Nullable<int>> BGS_IsRankSent(string empID)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("BGS_IsRankSent", empIDParameter);
        }

        public virtual ObjectResult<Nullable<bool>> BGS_IsVendorValid(string employeeId)
        {
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("BGS_IsVendorValid", employeeIdParameter);
        }

        public virtual int BGS_QuarterMaster(string transType, Nullable<int> quarterID, string name, Nullable<int> year, string createdBy, string updatedBy)
        {
            var transTypeParameter = transType != null ?
                new ObjectParameter("TransType", transType) :
                new ObjectParameter("TransType", typeof(string));

            var quarterIDParameter = quarterID.HasValue ?
                new ObjectParameter("QuarterID", quarterID) :
                new ObjectParameter("QuarterID", typeof(int));

            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));

            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));

            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));

            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_QuarterMaster", transTypeParameter, quarterIDParameter, nameParameter, yearParameter, createdByParameter, updatedByParameter);
        }

        public virtual int BGS_ReopenGradingprocess(Nullable<int> statusId, Nullable<int> gradingId)
        {
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));

            var gradingIdParameter = gradingId.HasValue ?
                new ObjectParameter("GradingId", gradingId) :
                new ObjectParameter("GradingId", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_ReopenGradingprocess", statusIdParameter, gradingIdParameter);
        }

        public virtual int BGS_SaveGradingMaster(Nullable<int> gradingId, Nullable<int> quarterId, string quarterName, Nullable<System.DateTime> dueDate, Nullable<int> statusId, string empId, Nullable<bool> isConfirm, string createdBy, string updatedBy)
        {
            var gradingIdParameter = gradingId.HasValue ?
                new ObjectParameter("GradingId", gradingId) :
                new ObjectParameter("GradingId", typeof(int));

            var quarterIdParameter = quarterId.HasValue ?
                new ObjectParameter("QuarterId", quarterId) :
                new ObjectParameter("QuarterId", typeof(int));

            var quarterNameParameter = quarterName != null ?
                new ObjectParameter("QuarterName", quarterName) :
                new ObjectParameter("QuarterName", typeof(string));

            var dueDateParameter = dueDate.HasValue ?
                new ObjectParameter("DueDate", dueDate) :
                new ObjectParameter("DueDate", typeof(System.DateTime));

            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));

            var empIdParameter = empId != null ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(string));

            var isConfirmParameter = isConfirm.HasValue ?
                new ObjectParameter("IsConfirm", isConfirm) :
                new ObjectParameter("IsConfirm", typeof(bool));

            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));

            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_SaveGradingMaster", gradingIdParameter, quarterIdParameter, quarterNameParameter, dueDateParameter, statusIdParameter, empIdParameter, isConfirmParameter, createdByParameter, updatedByParameter);
        }

        public virtual int BGS_SaveWeightMaster(Nullable<int> weightId, Nullable<int> roleID, Nullable<int> depID, Nullable<double> weight, string empId)
        {
            var weightIdParameter = weightId.HasValue ?
                new ObjectParameter("WeightId", weightId) :
                new ObjectParameter("WeightId", typeof(int));

            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));

            var depIDParameter = depID.HasValue ?
                new ObjectParameter("DepID", depID) :
                new ObjectParameter("DepID", typeof(int));

            var weightParameter = weight.HasValue ?
                new ObjectParameter("Weight", weight) :
                new ObjectParameter("Weight", typeof(double));

            var empIdParameter = empId != null ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_SaveWeightMaster", weightIdParameter, roleIDParameter, depIDParameter, weightParameter, empIdParameter);
        }

        public virtual ObjectResult<string> BGS_SearchUser(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BGS_SearchUser", searchParameter);
        }

        public virtual int BGS_UpdateEmailStatus(Nullable<bool> emailStatus, Nullable<int> brokerNameId)
        {
            var emailStatusParameter = emailStatus.HasValue ?
                new ObjectParameter("EmailStatus", emailStatus) :
                new ObjectParameter("EmailStatus", typeof(bool));

            var brokerNameIdParameter = brokerNameId.HasValue ?
                new ObjectParameter("BrokerNameId", brokerNameId) :
                new ObjectParameter("BrokerNameId", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_UpdateEmailStatus", emailStatusParameter, brokerNameIdParameter);
        }

        public virtual int BGS_UpdateVoteMasterStatus(string type, Nullable<int> gradingID, string empID, string userTypeName)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));

            var gradingIDParameter = gradingID.HasValue ?
                new ObjectParameter("GradingID", gradingID) :
                new ObjectParameter("GradingID", typeof(int));

            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            var userTypeNameParameter = userTypeName != null ?
                new ObjectParameter("UserTypeName", userTypeName) :
                new ObjectParameter("UserTypeName", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_UpdateVoteMasterStatus", typeParameter, gradingIDParameter, empIDParameter, userTypeNameParameter);
        }

        public virtual int BGS_User_StatusChange(string eMPLOYEEID, Nullable<bool> iSACITVE, Nullable<bool> iSFORCE, string cREATEDBY)
        {
            var eMPLOYEEIDParameter = eMPLOYEEID != null ?
                new ObjectParameter("EMPLOYEEID", eMPLOYEEID) :
                new ObjectParameter("EMPLOYEEID", typeof(string));

            var iSACITVEParameter = iSACITVE.HasValue ?
                new ObjectParameter("ISACITVE", iSACITVE) :
                new ObjectParameter("ISACITVE", typeof(bool));

            var iSFORCEParameter = iSFORCE.HasValue ?
                new ObjectParameter("ISFORCE", iSFORCE) :
                new ObjectParameter("ISFORCE", typeof(bool));

            var cREATEDBYParameter = cREATEDBY != null ?
                new ObjectParameter("CREATEDBY", cREATEDBY) :
                new ObjectParameter("CREATEDBY", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_User_StatusChange", eMPLOYEEIDParameter, iSACITVEParameter, iSFORCEParameter, cREATEDBYParameter);
        }

        public virtual int BGS_WeightMaster(Nullable<int> weightId, Nullable<int> roleID, Nullable<int> depID, Nullable<double> weight, string createdBy, string updatedBy, string empId)
        {
            var weightIdParameter = weightId.HasValue ?
                new ObjectParameter("WeightId", weightId) :
                new ObjectParameter("WeightId", typeof(int));

            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));

            var depIDParameter = depID.HasValue ?
                new ObjectParameter("DepID", depID) :
                new ObjectParameter("DepID", typeof(int));

            var weightParameter = weight.HasValue ?
                new ObjectParameter("Weight", weight) :
                new ObjectParameter("Weight", typeof(double));

            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));

            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));

            var empIdParameter = empId != null ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_WeightMaster", weightIdParameter, roleIDParameter, depIDParameter, weightParameter, createdByParameter, updatedByParameter, empIdParameter);
        }

        public virtual ObjectResult<Check_UserAuthentication_Result> Check_UserAuthentication(string employeeId, string password)
        {
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));

            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Check_UserAuthentication_Result>("Check_UserAuthentication", employeeIdParameter, passwordParameter);
        }

        public virtual ObjectResult<Nullable<int>> GetGradingStatus(string empID)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetGradingStatus", empIDParameter);
        }

        public virtual ObjectResult<GetMenuItem_Employee_Result> GetMenuItem_Employee(string employeeId)
        {
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMenuItem_Employee_Result>("GetMenuItem_Employee", employeeIdParameter);
        }

        public virtual ObjectResult<Nullable<int>> IsPageValidForUser(string empID, string pageName)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));

            var pageNameParameter = pageName != null ?
                new ObjectParameter("PageName", pageName) :
                new ObjectParameter("PageName", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("IsPageValidForUser", empIDParameter, pageNameParameter);
        }

        public virtual ObjectResult<Nullable<int>> IsUserExists(string empId, string emailID, string brokerName, Nullable<int> dofacode)
        {
            var empIdParameter = empId != null ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(string));

            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));

            var brokerNameParameter = brokerName != null ?
                new ObjectParameter("BrokerName", brokerName) :
                new ObjectParameter("BrokerName", typeof(string));

            var DofaCodeParameter = dofacode.HasValue ?
                new ObjectParameter("DofaCode", dofacode) :
                new ObjectParameter("DofaCode", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("IsUserExists", empIdParameter, emailIDParameter, brokerNameParameter, DofaCodeParameter);
        }

        public virtual ObjectResult<SP_CheckUserEmployeeId_Result> SP_CheckUserEmployeeId(string employeeId)
        {
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CheckUserEmployeeId_Result>("SP_CheckUserEmployeeId", employeeIdParameter);
        }

        public virtual ObjectResult<string> BGS_GetALLBrokerAnalyst(string brokerName)
        {
            var brokerNameParameter = brokerName != null ?
                new ObjectParameter("BrokerName", brokerName) :
                new ObjectParameter("BrokerName", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BGS_GetALLBrokerAnalyst", brokerNameParameter);
        }

        public virtual ObjectResult<BGS_GetBrokerUploadData_Result> BGS_GetBrokerUploadData(string brokerName)
        {
            var brokerNameParameter = brokerName != null ?
                new ObjectParameter("BrokerName", brokerName) :
                new ObjectParameter("BrokerName", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BGS_GetBrokerUploadData_Result>("BGS_GetBrokerUploadData", brokerNameParameter);
        }

        public virtual int BGS_InsertBrokerConfigforBrokerEmail(Nullable<int> brokerNameId, Nullable<int> quarterId, Nullable<bool> emailStatus)
        {
            var brokerNameIdParameter = brokerNameId.HasValue ?
                new ObjectParameter("BrokerNameId", brokerNameId) :
                new ObjectParameter("BrokerNameId", typeof(int));

            var quarterIdParameter = quarterId.HasValue ?
                new ObjectParameter("QuarterId", quarterId) :
                new ObjectParameter("QuarterId", typeof(int));

            var emailStatusParameter = emailStatus.HasValue ?
                new ObjectParameter("EmailStatus", emailStatus) :
                new ObjectParameter("EmailStatus", typeof(bool));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_InsertBrokerConfigforBrokerEmail", brokerNameIdParameter, quarterIdParameter, emailStatusParameter);
        }

        public virtual int BGS_InsertUpdateVoteMAster()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_InsertUpdateVoteMAster");
        }

        public virtual ObjectResult<Nullable<int>> BGS_IsAuthenticateBroker(string empId, string password)
        {
            var empIdParameter = empId != null ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(string));

            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("BGS_IsAuthenticateBroker", empIdParameter, passwordParameter);
        }

        public virtual int BGS_UploadBrokerAnalystDetails(string brokerName)
        {
            var brokerNameParameter = brokerName != null ?
                new ObjectParameter("BrokerName", brokerName) :
                new ObjectParameter("BrokerName", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BGS_UploadBrokerAnalystDetails", brokerNameParameter);
        }
    }
}
