//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoteMaster
    {
        public int VoteID { get; set; }
        public Nullable<decimal> Vote { get; set; }
        public Nullable<int> BrokerID { get; set; }
        public Nullable<int> GradingID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> DelStatus { get; set; }
        public Nullable<int> MaxLimit { get; set; }
        public string AnalystName { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<int> BrokerNameId { get; set; }
        public string FMComments { get; set; }
        public string RMComment { get; set; }
        public Nullable<int> ReasonID { get; set; }
    
        public virtual BrokerNameMaster BrokerNameMaster { get; set; }
        public virtual GradingMaster GradingMaster { get; set; }
        public virtual DOD_DOFAReason DOD_DOFAReason { get; set; }
    }
}
